version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/examples/hello"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
