# action.yml
name: 'cargo contracts'
description: 'Cargo command wrapper'
inputs:
  cargo-cmd:  # id of input
    description: 'Cargo command'
    required: true
    default: 'versions.sh'
  working-directory:
    description: 'default work dir'
    required: true
    default: '.'
runs:
  using: composite
  steps:
    - name: Store environment
      id: storeenv
      env:
        REF: "docker://openactionrs/action-cargo:${{ github.action_ref }}"
        ACTION_REF: ${{github.action_ref}}
      run: echo "ACTION_REF=${{ ACTION_REF }}" >> $GITHUB_OUTPUT
    - name: execute
      using: 'docker'
      image: "docker://openactionrs/action-cargo:$ACTION_REF"
      args:
        - ${{inputs.working-directory}}
        - ${{inputs.cargo-cmd}}
